### ISSUE TITLE
Добавить в сборку стилей автопрефиксер

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#317]
Сейчас в сборке только Sass и минификация и в стилях [бывает такое](https://github.com/Y-Doka/y-doka.site/blob/master/src/assets/styles/components/_aside.scss#L55-L58):

```scss
    &_shadow {
      -webkit-box-shadow: 0px -4px 4px 0px rgba(183, 183, 183, 0.25);
      -moz-box-shadow: 0px -4px 4px 0px rgba(183, 183, 183, 0.25);
      box-shadow: 0px -4px 4px 0px rgba(183, 183, 183, 0.25);
      background: $nb-grey-background;
    }
```

Что конечно избыточно для современных браузеров, в которых мы тестируем.
