### ISSUE TITLE
Поработать над картинками

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#398]
У нас очень большие картинки на десктопе - https://y-doka.site/js/long/oop/
![2020-12-22_21-27-36](https://user-images.githubusercontent.com/50330458/102920896-86acf180-449c-11eb-9d4b-653f5819a727.png)

Это связано с тем, что нельзя добавлять к картинкам классы, ограничивающие размер картинки. 

Решение предлагается следующее

Можем ограничивать размер картинки классом-обёрткой, как это сделано у таблиц

```markdown
<div class="article__table article__table_all-half">

| HTML 4.01 |  |
| --- | --- |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">` | Строгий синтаксис HTML |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">` | Переходный синтаксис HTML |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">` | В HTML-документе применяются фреймы |

</div>
```

[смотреть пример применения](https://y-doka.site/html/doka/doctype/), но там `<details>`, но не суть

```scss
&__table {
    & table {
      width: 100%;
      margin: 1em 0;

      & th, & td {
        padding: 0 .5em;
      }
    }

    &_all-half {
      & table {
        & th, & td {
          width: 50%;
        }
      }
    }
```

[смотреть scss](https://github.com/Y-Doka/y-doka.site/blob/master/src/assets/styles/components/_article.scss#L70)

Т.е. сделать например 

```markdown
<div class="images images_quarter">

![alt](/assets/images/posts/js/oop/screenshot-2.png)

</div>
```

```scss
&__images {
   &_quarter {
       & img {
          max-width: 25%;
          
          @media screen and (max-width: 425px) {
              max-width: 100%;
          }
       }
   }
}
```

С выдачей вот такой

```html
<div class="images images_quarter">
    <img src="/assets/images/posts/js/oop/screenshot-2.png" alt="alt">
</div>
```

## Дополнительная задача 

К обсуждению

Сейчас у нас картинки формата 

```markdown
![alt](/assets/images/posts/js/oop/screenshot-2.png)
```

Выводятся вот так

```html
<p>
    <img src="/assets/images/posts/js/oop/screenshot-2.png" alt="alt">
</p>
```

Не лучше ли настроить eleventy, чтобы получали вот так:

```html
<img src="/assets/images/posts/js/oop/screenshot-2.png" alt="alt">
```

т.е. без лишней обёртки?
