### ISSUE TITLE
Убрать из всех медиа screen and

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#430]
Когда мы пишем такой код:

```css
body {
  color: black;
}

@media screen and (…) {
  color: white;
}
```

Это значит:

1. Цвет на всех медиа будет чёрным (экран, печать)
2. Цвет **только** на экране (и при каких-то условиях) будет белым.

Я уверен, что мы нигде не имеем в виду это «только на экране». Достаточно писать:

```css
@media (…) {
  /* */
}
```
