### ISSUE TITLE
Дописать тему для кода без языка

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#517]
Сейчас в стилях глобальные селекторы с выборкой по атрибутам. Это само по себе пугает:

```scss
code[class*="language-"],
pre[class*="language-"] {
  color: #f8f8f2;
  text-shadow: 0 1px rgba(0, 0, 0, 0.3);
  font-family: Consolas, Monaco, 'Andale Mono', monospace;
  direction: ltr;
  text-align: left;
  white-space: pre;
  word-spacing: normal;
  word-break: normal;
  line-height: 1.5;

  -moz-tab-size: 4;
  -o-tab-size: 4;
  tab-size: 4;

  -webkit-hyphens: none;
  -moz-hyphens: none;
  -ms-hyphens: none;
  hyphens: none;
}
```

Нет языка — нет атрибутов, а значит блок кода превращается в тыкву:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/105274/107394525-0bb39f00-6b0d-11eb-9d76-002209ebc99c.png">

Нужно поправить селекторы, чтобы применимость блоков кода не зависела от атрибутов.
