### ISSUE TITLE
Убрать из  MD-файлов пустые поля

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#545]
Как сейчас:

```yml
title: ":active"
name: active
author: ABatickaya
co-authors:
designers:
contributors:
```

Можно лучше:

```yml
title: ":active"
name: active
author: ABatickaya
```

Это позволяет проверять наличие полей более просто `{% if designers %}`, а сейчас приходится проверять длину поля, а не его наличие. Ну и вообще кажется так становится чище: нет информации — нет поля, есть информация — добавляем.

**Comment by furtivite** [comment]
Согласен, но надо заодно написать документацию, какие поля используются или могут использоваться. 

Не забыть в документацию добавить про 

```yml
cover:
  desktop: 'desktop.png'
  mobile: 'mobile.png'
  alt: 'Умная собака подозрительно смотрит'
```
