### ISSUE TITLE
Отрефакторить article__code в демках

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#675]
У нас сейчас многие (не все) демки оборачиваются во фрагмент БЭМ-блока, судя по синтаксису, но лучше бы мы такое делали либо правильно, либо сильно проще:

```html
<div class="article__code">
```

Это всё идёт и доки по контрибьютингу, но я не понимаю мотивации — раз у нас демки внутри фрейма и со своими стилями.

> ```html
> 
> <style>
>   {% include './index.css' %}
> </style>
> 
> <div class="article__code" id="my-demo"></div>
> 
> <script>
>   {% include './index.js' %}
> </script>
> ```
> 
> Добавление класса article\_\_code является обязательным, он даёт черную рамку и усиливает специфичность.

**Comment by pepelsbey** [comment]
@furtivite ты наверное знаешь что-то про этот класс?

**Comment by furtivite** [comment]
Эта обёртка нужна 
1. Для усиления специфичности, чтобы можно было указывать в стилях как 

```css
.article__code .demo {
    /* какие-то стили */
}
```

2. Чтобы добавить [единые стили](https://github.com/Y-Doka/y-doka.site/blob/master/src/assets/styles/components/_article.scss) и обрамляющую рамку чёрного цвета как на материнском проекте

```scss
.article {
    /* другие стили*/

    &__code {
        border: 1px solid #18191C;
        position: relative;

        &:after {
          content: "Результат";
          position: absolute;
          right: 10px;
          top: 10px;
          opacity: 0.5;
          color: white;
          font-family: "Inter", Arial, sans-serif;
          font-size: 0.625em;
          text-transform: uppercase;
          user-select: none;
        }
    }
}

```
